### ISSUE TITLE
"report total" empty since deleting all my tasks

### ISSUE THREAD

**Issue by tshepang** [dinAlt/yatt#2]
In tested the tool for a day, and was pleased. I then deleted all tasks, and now starting a workday, I see the reporting functionality does not work.

```
❯ yatt start work::admin
Starting...

Interval info:
  Task: work > admin
  Started: just now

❯ # do stuff

❯ yatt stop
Stopping...

Interval info:
  Task: work > admin
  Started: 11:58:00 (13 seconds ago)
  Stopped: just now

❯ yatt list tasks

❯ yatt report total
                                                             Report: Total time.
                                              Period: 2020-05-11 00:00:00 - 2020-05-11 11:58:20

```

**Comment by dinAlt** [comment]
Hello, thanks for report! Did you use work::admin as task name in you tests? If you did and then delete d a task, it just marked deleted and therefore hidden in report. Yatt doesn't actually remove anything from database, it just marks records deleted. Looks like I need to handle attempts to start removed tasks.

P. S. English is not my native language, so fill free to let me know if you don't understand me)

**Comment by tshepang** [comment]
You are very clear, no worries.

I see now... it is indeed the case that I re-used the label `work:admin` in my tests, that's why it didn't work. In my case, I removed `work`, which meant it would not work with anything under it.

**Comment by dinAlt** [comment]
Ok then, I will fix it a little bit later. Didn’t think that someone would be interested in my little rust experiment without even crate description...)

**Comment by tshepang** [comment]
I like the love you put into it... the output looks good.

There's small things that can be changed/added to make it more smooth, but maybe I'll report them later.

**Comment by dinAlt** [comment]
Btw, my favorite yatts feature is working with dates and durations:

For `report total` command, default period is current day (from 00:00 til Now). But with `-p` option you can specify period in several forms:
- As interval: `DateBegin::DateEnd` or just `DateBegin` the DateEnd will be `NOW` then. Where `DateBegin` and `DateEnd` may be like **YYYY-MM-DD hh:mm** or  **DD.MM.YYYY hh:mm** or **D.M.YYYY** and so on...  You can omit the year and time parts.
- As offset: `[n]y` for years, `[n]m` for months, `[n]d` for days and `[n]h` for hours, where **n** is count (if **n** is omitted, it equals 1). Example: `2h` means last two hours, `m' - last month and so on...

For `add` and `trunc` commands duration may be like `[n]m` for minutes, `[n]h` for hours and `[n]d` for days.

**Comment by tshepang** [comment]
I do like, for example, `yatt report total --period 1w`. What are intervals for?

**Comment by dinAlt** [comment]
Oh yes, `w` is also work. Intervals in `--period` are for exact date range: `yatt report total -p 01.01.2020::01.02.2020` if you want a january report.
